sonar.projectKey=AxiosStock
sonar.projectName=Axios Stock
sonar.projectVersion=1.0

# Ruta del código fuente
sonar.sources=src

# Excluís node_modules y tests si no querés analizarlos
sonar.exclusions=**/node_modules/**,**/*.spec.ts


sonar.host.url=http://localhost:9000
sonar.token=sqp_70e8b00fc68a07921f80f0236fd55203481e647a
