-- Phase 1 + 2: Procurement + Expense tracking foundation
-- Scope:
-- - Purchase orders and goods receipts (operational stock intake)
-- - Supplier invoices and payments (financial outflows)
-- - Consolidated expense ledger (accrual + cash)

-- =============================================================================
-- 1) TABLES
-- =============================================================================

CREATE TABLE IF NOT EXISTS purchase_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  supplier_id UUID NOT NULL REFERENCES suppliers(id) ON DELETE RESTRICT,
  branch_id UUID NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  po_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  status VARCHAR(30) NOT NULL DEFAULT 'draft' CHECK (
    status IN ('draft', 'submitted', 'partially_received', 'received', 'cancelled')
  ),
  currency_code CHAR(3) NOT NULL DEFAULT 'UYU',
  ordered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expected_at TIMESTAMPTZ,
  received_at TIMESTAMPTZ,
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  notes TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  approved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (organization_id, po_number)
);

CREATE INDEX IF NOT EXISTS idx_purchase_orders_org_created_at ON purchase_orders(organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_org_status ON purchase_orders(organization_id, status);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_org_supplier ON purchase_orders(organization_id, supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_org_branch ON purchase_orders(organization_id, branch_id);

CREATE TABLE IF NOT EXISTS purchase_order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  purchase_order_id UUID NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  line_number INTEGER NOT NULL DEFAULT 1,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  variant_id UUID REFERENCES product_variants(id) ON DELETE RESTRICT,
  description TEXT,
  quantity_ordered INTEGER NOT NULL CHECK (quantity_ordered > 0),
  quantity_received INTEGER NOT NULL DEFAULT 0 CHECK (quantity_received >= 0),
  unit_cost NUMERIC(12,4) NOT NULL CHECK (unit_cost >= 0),
  tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT check_poi_received_lte_ordered CHECK (quantity_received <= quantity_ordered)
);

CREATE INDEX IF NOT EXISTS idx_purchase_order_items_po_id ON purchase_order_items(purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_items_org_product ON purchase_order_items(organization_id, product_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_items_org_variant ON purchase_order_items(organization_id, variant_id);

CREATE TABLE IF NOT EXISTS goods_receipts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  purchase_order_id UUID REFERENCES purchase_orders(id) ON DELETE SET NULL,
  supplier_id UUID NOT NULL REFERENCES suppliers(id) ON DELETE RESTRICT,
  branch_id UUID NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  receipt_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
  status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'posted', 'cancelled')),
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  notes TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  posted_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  posted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (organization_id, receipt_number)
);

CREATE INDEX IF NOT EXISTS idx_goods_receipts_org_created_at ON goods_receipts(organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_goods_receipts_org_status ON goods_receipts(organization_id, status);
CREATE INDEX IF NOT EXISTS idx_goods_receipts_org_supplier ON goods_receipts(organization_id, supplier_id);

CREATE TABLE IF NOT EXISTS goods_receipt_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  goods_receipt_id UUID NOT NULL REFERENCES goods_receipts(id) ON DELETE CASCADE,
  purchase_order_item_id UUID REFERENCES purchase_order_items(id) ON DELETE SET NULL,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  variant_id UUID REFERENCES product_variants(id) ON DELETE RESTRICT,
  quantity_received INTEGER NOT NULL CHECK (quantity_received > 0),
  unit_cost NUMERIC(12,4) NOT NULL CHECK (unit_cost >= 0),
  tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_goods_receipt_items_receipt_id ON goods_receipt_items(goods_receipt_id);
CREATE INDEX IF NOT EXISTS idx_goods_receipt_items_org_product ON goods_receipt_items(organization_id, product_id);
CREATE INDEX IF NOT EXISTS idx_goods_receipt_items_org_variant ON goods_receipt_items(organization_id, variant_id);

CREATE TABLE IF NOT EXISTS supplier_invoices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  supplier_id UUID NOT NULL REFERENCES suppliers(id) ON DELETE RESTRICT,
  branch_id UUID REFERENCES branches(id) ON DELETE SET NULL,
  purchase_order_id UUID REFERENCES purchase_orders(id) ON DELETE SET NULL,
  goods_receipt_id UUID REFERENCES goods_receipts(id) ON DELETE SET NULL,
  invoice_number VARCHAR(120) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'draft' CHECK (
    status IN ('draft', 'issued', 'partially_paid', 'paid', 'cancelled')
  ),
  issue_date DATE NOT NULL DEFAULT CURRENT_DATE,
  due_date DATE,
  currency_code CHAR(3) NOT NULL DEFAULT 'UYU',
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  paid_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  outstanding_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  notes TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  approved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (organization_id, supplier_id, invoice_number)
);

CREATE INDEX IF NOT EXISTS idx_supplier_invoices_org_created_at ON supplier_invoices(organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_invoices_org_status ON supplier_invoices(organization_id, status);
CREATE INDEX IF NOT EXISTS idx_supplier_invoices_org_supplier ON supplier_invoices(organization_id, supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invoices_org_due_date ON supplier_invoices(organization_id, due_date);

CREATE TABLE IF NOT EXISTS supplier_payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  supplier_invoice_id UUID NOT NULL REFERENCES supplier_invoices(id) ON DELETE RESTRICT,
  supplier_id UUID NOT NULL REFERENCES suppliers(id) ON DELETE RESTRICT,
  branch_id UUID REFERENCES branches(id) ON DELETE SET NULL,
  payment_method VARCHAR(50) NOT NULL,
  payment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
  status VARCHAR(20) NOT NULL DEFAULT 'posted' CHECK (status IN ('posted', 'reversed')),
  reference_number VARCHAR(120),
  notes TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  reversed_at TIMESTAMPTZ,
  reversed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_supplier_payments_org_created_at ON supplier_payments(organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_supplier_payments_org_invoice ON supplier_payments(organization_id, supplier_invoice_id);
CREATE INDEX IF NOT EXISTS idx_supplier_payments_org_supplier ON supplier_payments(organization_id, supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_payments_org_status ON supplier_payments(organization_id, status);

CREATE TABLE IF NOT EXISTS expense_ledger (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  branch_id UUID REFERENCES branches(id) ON DELETE SET NULL,
  supplier_id UUID REFERENCES suppliers(id) ON DELETE SET NULL,
  entry_kind VARCHAR(20) NOT NULL CHECK (entry_kind IN ('accrual', 'cash')),
  event_type VARCHAR(30) NOT NULL CHECK (
    event_type IN ('invoice', 'payment', 'payment_reversal', 'manual_adjustment')
  ),
  source_table VARCHAR(50) NOT NULL,
  source_id UUID NOT NULL,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  currency_code CHAR(3) NOT NULL DEFAULT 'UYU',
  gross_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  net_amount NUMERIC(12,2) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'posted' CHECK (status IN ('posted', 'cancelled')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_expense_ledger_org_occurred_at ON expense_ledger(organization_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_expense_ledger_org_kind_type ON expense_ledger(organization_id, entry_kind, event_type);
CREATE INDEX IF NOT EXISTS idx_expense_ledger_org_supplier ON expense_ledger(organization_id, supplier_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_expense_ledger_posted_source_event
  ON expense_ledger(source_table, source_id, event_type)
  WHERE status = 'posted';

-- =============================================================================
-- 2) TRIGGERS: updated_at
-- =============================================================================

DROP TRIGGER IF EXISTS update_purchase_orders_updated_at ON purchase_orders;
CREATE TRIGGER update_purchase_orders_updated_at
  BEFORE UPDATE ON purchase_orders
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_goods_receipts_updated_at ON goods_receipts;
CREATE TRIGGER update_goods_receipts_updated_at
  BEFORE UPDATE ON goods_receipts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_supplier_invoices_updated_at ON supplier_invoices;
CREATE TRIGGER update_supplier_invoices_updated_at
  BEFORE UPDATE ON supplier_invoices
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_supplier_payments_updated_at ON supplier_payments;
CREATE TRIGGER update_supplier_payments_updated_at
  BEFORE UPDATE ON supplier_payments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- 3) HELPER FUNCTIONS
-- =============================================================================

CREATE OR REPLACE FUNCTION recalculate_purchase_order_totals(p_purchase_order_id UUID)
RETURNS VOID AS $$
BEGIN
  UPDATE purchase_orders po
  SET
    subtotal = COALESCE(calc.subtotal, 0),
    tax_total = COALESCE(calc.tax_total, 0),
    discount_total = COALESCE(calc.discount_total, 0),
    total = COALESCE(calc.subtotal, 0) + COALESCE(calc.tax_total, 0) - COALESCE(calc.discount_total, 0),
    updated_at = NOW()
  FROM (
    SELECT
      purchase_order_id,
      SUM(quantity_ordered * unit_cost)::NUMERIC(12,2) AS subtotal,
      SUM(tax_amount)::NUMERIC(12,2) AS tax_total,
      SUM(discount_amount)::NUMERIC(12,2) AS discount_total
    FROM purchase_order_items
    WHERE purchase_order_id = p_purchase_order_id
    GROUP BY purchase_order_id
  ) calc
  WHERE po.id = calc.purchase_order_id;

  UPDATE purchase_orders
  SET subtotal = 0, tax_total = 0, discount_total = 0, total = 0, updated_at = NOW()
  WHERE id = p_purchase_order_id
    AND NOT EXISTS (SELECT 1 FROM purchase_order_items WHERE purchase_order_id = p_purchase_order_id);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION trg_recalculate_purchase_order_totals()
RETURNS TRIGGER AS $$
DECLARE
  v_purchase_order_id UUID;
BEGIN
  v_purchase_order_id := COALESCE(NEW.purchase_order_id, OLD.purchase_order_id);
  PERFORM recalculate_purchase_order_totals(v_purchase_order_id);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS recalculate_purchase_order_totals_on_items ON purchase_order_items;
CREATE TRIGGER recalculate_purchase_order_totals_on_items
  AFTER INSERT OR UPDATE OR DELETE ON purchase_order_items
  FOR EACH ROW EXECUTE FUNCTION trg_recalculate_purchase_order_totals();

CREATE OR REPLACE FUNCTION trg_sync_purchase_order_item_org()
RETURNS TRIGGER AS $$
BEGIN
  SELECT organization_id INTO NEW.organization_id
  FROM purchase_orders
  WHERE id = NEW.purchase_order_id;

  IF NEW.organization_id IS NULL THEN
    RAISE EXCEPTION 'purchase_order % not found', NEW.purchase_order_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS sync_purchase_order_item_org ON purchase_order_items;
CREATE TRIGGER sync_purchase_order_item_org
  BEFORE INSERT OR UPDATE ON purchase_order_items
  FOR EACH ROW EXECUTE FUNCTION trg_sync_purchase_order_item_org();

CREATE OR REPLACE FUNCTION trg_sync_goods_receipt_org()
RETURNS TRIGGER AS $$
DECLARE
  v_po RECORD;
BEGIN
  IF NEW.purchase_order_id IS NOT NULL THEN
    SELECT organization_id, supplier_id, branch_id, currency_code
    INTO v_po
    FROM purchase_orders
    WHERE id = NEW.purchase_order_id;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'purchase_order % not found', NEW.purchase_order_id;
    END IF;

    NEW.organization_id := v_po.organization_id;
    NEW.supplier_id := COALESCE(NEW.supplier_id, v_po.supplier_id);
    NEW.branch_id := COALESCE(NEW.branch_id, v_po.branch_id);
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS sync_goods_receipt_org ON goods_receipts;
CREATE TRIGGER sync_goods_receipt_org
  BEFORE INSERT OR UPDATE ON goods_receipts
  FOR EACH ROW EXECUTE FUNCTION trg_sync_goods_receipt_org();

CREATE OR REPLACE FUNCTION trg_sync_goods_receipt_item_org()
RETURNS TRIGGER AS $$
BEGIN
  SELECT organization_id INTO NEW.organization_id
  FROM goods_receipts
  WHERE id = NEW.goods_receipt_id;

  IF NEW.organization_id IS NULL THEN
    RAISE EXCEPTION 'goods_receipt % not found', NEW.goods_receipt_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS sync_goods_receipt_item_org ON goods_receipt_items;
CREATE TRIGGER sync_goods_receipt_item_org
  BEFORE INSERT OR UPDATE ON goods_receipt_items
  FOR EACH ROW EXECUTE FUNCTION trg_sync_goods_receipt_item_org();

CREATE OR REPLACE FUNCTION trg_sync_supplier_payment_context()
RETURNS TRIGGER AS $$
DECLARE
  v_invoice RECORD;
BEGIN
  SELECT organization_id, supplier_id, branch_id
  INTO v_invoice
  FROM supplier_invoices
  WHERE id = NEW.supplier_invoice_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'supplier_invoice % not found', NEW.supplier_invoice_id;
  END IF;

  NEW.organization_id := v_invoice.organization_id;
  NEW.supplier_id := v_invoice.supplier_id;
  NEW.branch_id := COALESCE(NEW.branch_id, v_invoice.branch_id);

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS sync_supplier_payment_context ON supplier_payments;
CREATE TRIGGER sync_supplier_payment_context
  BEFORE INSERT OR UPDATE ON supplier_payments
  FOR EACH ROW EXECUTE FUNCTION trg_sync_supplier_payment_context();

CREATE OR REPLACE FUNCTION trg_sync_supplier_invoice_outstanding()
RETURNS TRIGGER AS $$
BEGIN
  NEW.paid_amount := COALESCE(NEW.paid_amount, 0);
  NEW.total_amount := COALESCE(NEW.total_amount, 0);
  NEW.outstanding_amount := GREATEST(NEW.total_amount - NEW.paid_amount, 0);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS sync_supplier_invoice_outstanding ON supplier_invoices;
CREATE TRIGGER sync_supplier_invoice_outstanding
  BEFORE INSERT OR UPDATE ON supplier_invoices
  FOR EACH ROW EXECUTE FUNCTION trg_sync_supplier_invoice_outstanding();

CREATE OR REPLACE FUNCTION sync_supplier_invoice_payment_totals(p_supplier_invoice_id UUID)
RETURNS VOID AS $$
DECLARE
  v_paid NUMERIC(12,2);
BEGIN
  SELECT COALESCE(SUM(amount), 0)::NUMERIC(12,2)
  INTO v_paid
  FROM supplier_payments
  WHERE supplier_invoice_id = p_supplier_invoice_id
    AND status = 'posted';

  UPDATE supplier_invoices
  SET
    paid_amount = v_paid,
    outstanding_amount = GREATEST(total_amount - v_paid, 0),
    status = CASE
      WHEN status = 'cancelled' THEN 'cancelled'
      WHEN v_paid <= 0 AND status = 'draft' THEN 'draft'
      WHEN v_paid <= 0 THEN 'issued'
      WHEN v_paid >= total_amount THEN 'paid'
      ELSE 'partially_paid'
    END,
    updated_at = NOW()
  WHERE id = p_supplier_invoice_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION trg_sync_supplier_invoice_payment_totals()
RETURNS TRIGGER AS $$
DECLARE
  v_invoice_id UUID;
BEGIN
  v_invoice_id := COALESCE(NEW.supplier_invoice_id, OLD.supplier_invoice_id);
  PERFORM sync_supplier_invoice_payment_totals(v_invoice_id);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS sync_supplier_invoice_payment_totals_on_payments ON supplier_payments;
CREATE TRIGGER sync_supplier_invoice_payment_totals_on_payments
  AFTER INSERT OR UPDATE OR DELETE ON supplier_payments
  FOR EACH ROW EXECUTE FUNCTION trg_sync_supplier_invoice_payment_totals();

-- =============================================================================
-- 4) POSTING FUNCTIONS (transactional)
-- =============================================================================

CREATE OR REPLACE FUNCTION post_goods_receipt(p_goods_receipt_id UUID)
RETURNS UUID AS $$
DECLARE
  v_receipt goods_receipts%ROWTYPE;
  v_item RECORD;
  v_branch_inventory_id UUID;
  v_previous_stock INTEGER;
  v_new_stock INTEGER;
BEGIN
  SELECT *
  INTO v_receipt
  FROM goods_receipts
  WHERE id = p_goods_receipt_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'goods_receipt % not found', p_goods_receipt_id;
  END IF;

  IF v_receipt.status <> 'draft' THEN
    RAISE EXCEPTION 'goods_receipt % is not in draft status', p_goods_receipt_id;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM goods_receipt_items WHERE goods_receipt_id = p_goods_receipt_id) THEN
    RAISE EXCEPTION 'goods_receipt % has no items', p_goods_receipt_id;
  END IF;

  FOR v_item IN
    SELECT *
    FROM goods_receipt_items
    WHERE goods_receipt_id = p_goods_receipt_id
  LOOP
    IF v_item.variant_id IS NOT NULL THEN
      INSERT INTO branch_inventory (branch_id, product_id, variant_id, stock, min_stock, low_stock_threshold)
      VALUES (v_receipt.branch_id, NULL, v_item.variant_id, 0, 0, 10)
      ON CONFLICT (branch_id, variant_id) WHERE variant_id IS NOT NULL DO NOTHING;

      SELECT id, stock INTO v_branch_inventory_id, v_previous_stock
      FROM branch_inventory
      WHERE branch_id = v_receipt.branch_id
        AND variant_id = v_item.variant_id
        AND product_id IS NULL
      FOR UPDATE;
    ELSE
      INSERT INTO branch_inventory (branch_id, product_id, variant_id, stock, min_stock, low_stock_threshold)
      VALUES (v_receipt.branch_id, v_item.product_id, NULL, 0, 0, 10)
      ON CONFLICT (branch_id, product_id) WHERE product_id IS NOT NULL DO NOTHING;

      SELECT id, stock INTO v_branch_inventory_id, v_previous_stock
      FROM branch_inventory
      WHERE branch_id = v_receipt.branch_id
        AND product_id = v_item.product_id
        AND variant_id IS NULL
      FOR UPDATE;
    END IF;

    IF v_branch_inventory_id IS NULL THEN
      RAISE EXCEPTION 'could not resolve branch_inventory entry for receipt item %', v_item.id;
    END IF;

    v_new_stock := COALESCE(v_previous_stock, 0) + v_item.quantity_received;

    UPDATE branch_inventory
    SET stock = v_new_stock,
        updated_at = NOW()
    WHERE id = v_branch_inventory_id;

    PERFORM create_inventory_movement(
      v_branch_inventory_id,
      'receipt',
      v_item.quantity_received,
      COALESCE(v_previous_stock, 0),
      v_new_stock,
      p_goods_receipt_id,
      'goods_receipt',
      COALESCE(v_item.notes, v_receipt.notes),
      v_receipt.supplier_id
    );
  END LOOP;

  UPDATE goods_receipts
  SET status = 'posted',
      posted_by = auth.uid(),
      posted_at = NOW(),
      updated_at = NOW()
  WHERE id = p_goods_receipt_id;

  -- Update PO progress if the receipt is linked to a PO
  IF v_receipt.purchase_order_id IS NOT NULL THEN
    UPDATE purchase_order_items poi
    SET quantity_received = COALESCE(src.qty_received, 0)
    FROM (
      SELECT
        gri.purchase_order_item_id,
        SUM(gri.quantity_received)::INTEGER AS qty_received
      FROM goods_receipt_items gri
      JOIN goods_receipts gr ON gr.id = gri.goods_receipt_id
      WHERE gr.status = 'posted'
        AND gri.purchase_order_item_id IS NOT NULL
      GROUP BY gri.purchase_order_item_id
    ) src
    WHERE poi.id = src.purchase_order_item_id
      AND poi.purchase_order_id = v_receipt.purchase_order_id;

    UPDATE purchase_orders po
    SET
      status = CASE
        WHEN EXISTS (
          SELECT 1 FROM purchase_order_items poi
          WHERE poi.purchase_order_id = po.id
            AND poi.quantity_received < poi.quantity_ordered
        ) THEN 'partially_received'
        ELSE 'received'
      END,
      received_at = CASE
        WHEN NOT EXISTS (
          SELECT 1 FROM purchase_order_items poi
          WHERE poi.purchase_order_id = po.id
            AND poi.quantity_received < poi.quantity_ordered
        ) THEN NOW()
        ELSE po.received_at
      END,
      updated_at = NOW()
    WHERE po.id = v_receipt.purchase_order_id
      AND po.status <> 'cancelled';
  END IF;

  RETURN p_goods_receipt_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION post_supplier_invoice(p_supplier_invoice_id UUID)
RETURNS UUID AS $$
DECLARE
  v_invoice supplier_invoices%ROWTYPE;
BEGIN
  SELECT *
  INTO v_invoice
  FROM supplier_invoices
  WHERE id = p_supplier_invoice_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'supplier_invoice % not found', p_supplier_invoice_id;
  END IF;

  IF v_invoice.status = 'cancelled' THEN
    RAISE EXCEPTION 'supplier_invoice % is cancelled', p_supplier_invoice_id;
  END IF;

  IF v_invoice.status = 'draft' THEN
    UPDATE supplier_invoices
    SET status = 'issued',
        paid_amount = COALESCE(paid_amount, 0),
        outstanding_amount = GREATEST(total_amount - COALESCE(paid_amount, 0), 0),
        updated_at = NOW()
    WHERE id = p_supplier_invoice_id;
  END IF;

  INSERT INTO expense_ledger (
    organization_id,
    branch_id,
    supplier_id,
    entry_kind,
    event_type,
    source_table,
    source_id,
    occurred_at,
    currency_code,
    gross_amount,
    tax_amount,
    discount_amount,
    net_amount,
    status,
    metadata,
    created_by
  )
  VALUES (
    v_invoice.organization_id,
    v_invoice.branch_id,
    v_invoice.supplier_id,
    'accrual',
    'invoice',
    'supplier_invoices',
    v_invoice.id,
    NOW(),
    v_invoice.currency_code,
    v_invoice.subtotal,
    v_invoice.tax_total,
    v_invoice.discount_total,
    v_invoice.total_amount,
    'posted',
    jsonb_build_object('invoice_number', v_invoice.invoice_number),
    auth.uid()
  )
  ON CONFLICT DO NOTHING;

  RETURN p_supplier_invoice_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION register_supplier_payment(
  p_supplier_invoice_id UUID,
  p_amount NUMERIC(12,2),
  p_payment_method VARCHAR(50),
  p_payment_date TIMESTAMPTZ DEFAULT NOW(),
  p_reference_number VARCHAR(120) DEFAULT NULL,
  p_notes TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
  v_invoice supplier_invoices%ROWTYPE;
  v_payment_id UUID;
BEGIN
  IF p_amount <= 0 THEN
    RAISE EXCEPTION 'payment amount must be greater than 0';
  END IF;

  SELECT *
  INTO v_invoice
  FROM supplier_invoices
  WHERE id = p_supplier_invoice_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'supplier_invoice % not found', p_supplier_invoice_id;
  END IF;

  IF v_invoice.status = 'cancelled' THEN
    RAISE EXCEPTION 'cannot pay cancelled invoice %', p_supplier_invoice_id;
  END IF;

  IF v_invoice.outstanding_amount <= 0 THEN
    RAISE EXCEPTION 'invoice % has no outstanding amount', p_supplier_invoice_id;
  END IF;

  IF p_amount > v_invoice.outstanding_amount THEN
    RAISE EXCEPTION 'payment amount (%) exceeds outstanding amount (%)', p_amount, v_invoice.outstanding_amount;
  END IF;

  INSERT INTO supplier_payments (
    organization_id,
    supplier_invoice_id,
    supplier_id,
    branch_id,
    payment_method,
    payment_date,
    amount,
    status,
    reference_number,
    notes,
    created_by
  )
  VALUES (
    v_invoice.organization_id,
    v_invoice.id,
    v_invoice.supplier_id,
    v_invoice.branch_id,
    p_payment_method,
    COALESCE(p_payment_date, NOW()),
    p_amount,
    'posted',
    p_reference_number,
    p_notes,
    auth.uid()
  )
  RETURNING id INTO v_payment_id;

  RETURN v_payment_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================================================
-- 5) EXPENSE LEDGER INTEGRATION
-- =============================================================================

CREATE OR REPLACE FUNCTION trg_expense_ledger_on_supplier_payment()
RETURNS TRIGGER AS $$
DECLARE
  v_invoice supplier_invoices%ROWTYPE;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.status = 'posted' THEN
      SELECT * INTO v_invoice FROM supplier_invoices WHERE id = NEW.supplier_invoice_id;

      INSERT INTO expense_ledger (
        organization_id,
        branch_id,
        supplier_id,
        entry_kind,
        event_type,
        source_table,
        source_id,
        occurred_at,
        currency_code,
        gross_amount,
        tax_amount,
        discount_amount,
        net_amount,
        status,
        metadata,
        created_by
      )
      VALUES (
        NEW.organization_id,
        NEW.branch_id,
        NEW.supplier_id,
        'cash',
        'payment',
        'supplier_payments',
        NEW.id,
        NEW.payment_date,
        COALESCE(v_invoice.currency_code, 'UYU'),
        NEW.amount,
        0,
        0,
        NEW.amount,
        'posted',
        jsonb_build_object(
          'supplier_invoice_id', NEW.supplier_invoice_id,
          'payment_method', NEW.payment_method,
          'reference_number', NEW.reference_number
        ),
        NEW.created_by
      )
      ON CONFLICT DO NOTHING;
    END IF;

    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    -- Reversal creates a compensating cash entry
    IF OLD.status = 'posted' AND NEW.status = 'reversed' THEN
      SELECT * INTO v_invoice FROM supplier_invoices WHERE id = NEW.supplier_invoice_id;

      INSERT INTO expense_ledger (
        organization_id,
        branch_id,
        supplier_id,
        entry_kind,
        event_type,
        source_table,
        source_id,
        occurred_at,
        currency_code,
        gross_amount,
        tax_amount,
        discount_amount,
        net_amount,
        status,
        metadata,
        created_by
      )
      VALUES (
        NEW.organization_id,
        NEW.branch_id,
        NEW.supplier_id,
        'cash',
        'payment_reversal',
        'supplier_payments',
        NEW.id,
        COALESCE(NEW.reversed_at, NOW()),
        COALESCE(v_invoice.currency_code, 'UYU'),
        -NEW.amount,
        0,
        0,
        -NEW.amount,
        'posted',
        jsonb_build_object(
          'supplier_invoice_id', NEW.supplier_invoice_id,
          'reversal_of_payment_id', NEW.id,
          'payment_method', NEW.payment_method
        ),
        COALESCE(NEW.reversed_by, NEW.created_by)
      )
      ON CONFLICT DO NOTHING;
    END IF;

    RETURN NEW;
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS expense_ledger_on_supplier_payment ON supplier_payments;
CREATE TRIGGER expense_ledger_on_supplier_payment
  AFTER INSERT OR UPDATE ON supplier_payments
  FOR EACH ROW EXECUTE FUNCTION trg_expense_ledger_on_supplier_payment();

-- =============================================================================
-- 6) RLS
-- =============================================================================

ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE goods_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE goods_receipt_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE supplier_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE supplier_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_ledger ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Purchase orders select" ON purchase_orders;
CREATE POLICY "Purchase orders select"
  ON purchase_orders FOR SELECT
  USING (organization_id IN (SELECT organization_id FROM organization_members WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "Purchase orders mutate" ON purchase_orders;
CREATE POLICY "Purchase orders mutate"
  ON purchase_orders FOR ALL
  USING (public.is_org_admin_or_manager(organization_id))
  WITH CHECK (public.is_org_admin_or_manager(organization_id));

DROP POLICY IF EXISTS "Purchase order items select" ON purchase_order_items;
CREATE POLICY "Purchase order items select"
  ON purchase_order_items FOR SELECT
  USING (organization_id IN (SELECT organization_id FROM organization_members WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "Purchase order items mutate" ON purchase_order_items;
CREATE POLICY "Purchase order items mutate"
  ON purchase_order_items FOR ALL
  USING (public.is_org_admin_or_manager(organization_id))
  WITH CHECK (public.is_org_admin_or_manager(organization_id));

DROP POLICY IF EXISTS "Goods receipts select" ON goods_receipts;
CREATE POLICY "Goods receipts select"
  ON goods_receipts FOR SELECT
  USING (organization_id IN (SELECT organization_id FROM organization_members WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "Goods receipts mutate" ON goods_receipts;
CREATE POLICY "Goods receipts mutate"
  ON goods_receipts FOR ALL
  USING (public.is_org_admin_or_manager(organization_id))
  WITH CHECK (public.is_org_admin_or_manager(organization_id));

DROP POLICY IF EXISTS "Goods receipt items select" ON goods_receipt_items;
CREATE POLICY "Goods receipt items select"
  ON goods_receipt_items FOR SELECT
  USING (organization_id IN (SELECT organization_id FROM organization_members WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "Goods receipt items mutate" ON goods_receipt_items;
CREATE POLICY "Goods receipt items mutate"
  ON goods_receipt_items FOR ALL
  USING (public.is_org_admin_or_manager(organization_id))
  WITH CHECK (public.is_org_admin_or_manager(organization_id));

DROP POLICY IF EXISTS "Supplier invoices select" ON supplier_invoices;
CREATE POLICY "Supplier invoices select"
  ON supplier_invoices FOR SELECT
  USING (organization_id IN (SELECT organization_id FROM organization_members WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "Supplier invoices mutate" ON supplier_invoices;
CREATE POLICY "Supplier invoices mutate"
  ON supplier_invoices FOR ALL
  USING (public.is_org_admin_or_manager(organization_id))
  WITH CHECK (public.is_org_admin_or_manager(organization_id));

DROP POLICY IF EXISTS "Supplier payments select" ON supplier_payments;
CREATE POLICY "Supplier payments select"
  ON supplier_payments FOR SELECT
  USING (organization_id IN (SELECT organization_id FROM organization_members WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "Supplier payments mutate" ON supplier_payments;
CREATE POLICY "Supplier payments mutate"
  ON supplier_payments FOR ALL
  USING (public.is_org_admin_or_manager(organization_id))
  WITH CHECK (public.is_org_admin_or_manager(organization_id));

DROP POLICY IF EXISTS "Expense ledger select" ON expense_ledger;
CREATE POLICY "Expense ledger select"
  ON expense_ledger FOR SELECT
  USING (organization_id IN (SELECT organization_id FROM organization_members WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "Expense ledger mutate" ON expense_ledger;
CREATE POLICY "Expense ledger mutate"
  ON expense_ledger FOR ALL
  USING (public.is_org_admin_or_manager(organization_id))
  WITH CHECK (public.is_org_admin_or_manager(organization_id));

-- =============================================================================
-- 7) COMMENTS
-- =============================================================================

COMMENT ON TABLE purchase_orders IS 'Cabecera de órdenes de compra a proveedor (Fase 1).';
COMMENT ON TABLE goods_receipts IS 'Recepción de mercadería (postea inventario al confirmar).';
COMMENT ON FUNCTION post_goods_receipt(UUID) IS 'Postea una recepción: actualiza stock, crea inventory_movements y actualiza estado de OC.';
COMMENT ON TABLE supplier_invoices IS 'Facturas de proveedor para gestión de deuda y egresos (Fase 2).';
COMMENT ON TABLE supplier_payments IS 'Pagos a proveedor. Soporta pago parcial y reverso.';
COMMENT ON FUNCTION register_supplier_payment(UUID, NUMERIC, VARCHAR, TIMESTAMPTZ, VARCHAR, TEXT) IS 'Registra un pago validando saldo pendiente de la factura.';
COMMENT ON TABLE expense_ledger IS 'Libro de egresos consolidado con entradas accrual y cash.';

